---
- name: validate connection is network_cli
  fail:
    msg: "expected connection network_cli, got {{ ansible_connection }}"
  when: ansible_connection != 'network_cli'

- name: check for required fact ansible_network_os
  fail:
    msg: "missing required fact: ansible_network_os"
  when: ansible_network_os is undefined

- name: run command on remote network node
  cli_get:
    command: "{{ command }}"
  register: command

- name: set contents fact
  set_fact:
    contents: "{{ command.stdout }}"

- name: parse output and return facts
  include_tasks: parse.yaml
  when: parser is defined

